### ISSUE TITLE
bots not spawn!

### ISSUE THREAD

**Issue by Mystik21** [G047/Agar.io-Bots#10]
I Think im doing all correct...but bots not spawn! What is wrong?
![immagine](https://cloud.githubusercontent.com/assets/22016209/18596857/974616d4-7c4b-11e6-9afc-749a198da6e7.png)

**Comment by G047** [comment]
Due to a recent agar.io patch they have prevented the proxies from connecting to agar.io hang tight bypass coming soon :)

**Comment by Wawy123** [comment]
hope u fix it

**Comment by Mystik21** [comment]
oh ok :D

**Comment by G047** [comment]
Ok bypassed agars patch
