### ISSUE TITLE
run.py

### ISSUE THREAD

**Issue by runekf** [G047/Agar.io-Bots#13]
Run.py wont start?

**Comment by Nick8fr32** [comment]
what does it do ??

**Comment by runekf** [comment]
It just closes in 0.1 second. I can't read whats inside.

**Comment by Nick8fr32** [comment]
https://www.youtube.com/watch?v=uXqTw5eO0Mw

**Comment by Mystik21** [comment]
same problem

**Comment by runekf** [comment]
No, it does recognize it. The older run.py does actually run.

**Comment by AgarPl4y3r** [comment]
ye it not work

**Comment by Nick8fr32** [comment]
it works for me after i did the things in the video but my bots still dont spawn in maybe i just found some shit proxies

**Comment by G047** [comment]
The bots are temporarily not working, until i find a more permant solution

**Comment by Nick8fr32** [comment]
okay

**Comment by G047** [comment]
Also this error is not with the code but your python configuration.
