### ISSUE TITLE
how to run pls help

### ISSUE THREAD

**Issue by Wawy123** [G047/Agar.io-Bots#15]
my friend have 450 bots but he wont tell how to run. he use this files

**Comment by fayizan** [comment]
Me too stuck at Python,what the actual python version is needed...

**Comment by G047** [comment]
You need python version 2.7

**Comment by fayizan** [comment]
@G047 thnk you so much,but I m getting this error
![screenshot_300](https://cloud.githubusercontent.com/assets/19163419/18607158/4954b7cc-7ce2-11e6-9fd1-c1b82f8d1316.png)

**Comment by fayizan** [comment]
ok I just saw the issue #10 ,good luck on fixing...!!

**Comment by Wawy123** [comment]
how to run it on vps????

**Comment by Wawy123** [comment]
and on wich vps?
