### ISSUE TITLE
Can you make the instructions more clear?

### ISSUE THREAD

**Issue by HappyyYT** [G047/Agar.io-Bots#17]
in the README.md, i don't get the instructions

I installed node.js, but you need to install python and pip? There's no version or download link.

When I did npm install, a node_modules folder pops up and it has nothing inside it.

**Comment by Mystik21** [comment]
go here and download python 2.7.12 https://www.python.org/downloads/ after it you can install on node these code npm install express figlet serve-index socket.io readline / pip install selenium

**Comment by HappyyYT** [comment]
@Mystik21 did, i dont get what you mean by 

> these code npm install express figlet serve-index socket.io readline / pip install selenium

**Comment by Mystik21** [comment]
open node.js command prompt and copy and paste this "npm install express figlet serve-index socket.io readline" and press enter,wait 1 min and copy and paste this "pip install selenium" and press again enter

**Comment by HappyyYT** [comment]
![image](https://cloud.githubusercontent.com/assets/9408910/18607658/8ee7a2b0-7cdb-11e6-94e0-a370be061395.png)

**Comment by G047** [comment]
@HappyyYT Google "how to add pip to path

**Comment by HappyyYT** [comment]
thanks @G047 it works :)

**Comment by SlimxaQ** [comment]
@G047 
Hey!

What do you think about create the free version of this and create the site to use it for free but more bots = Its cost.

I already making the site I'm working on design it more but looks great :D

Some screens:

1. http://screenshot.sh/ov4UMxq2eJ052
2. http://screenshot.sh/odxepLkoyLjC4
3. http://screenshot.sh/m3c7jWplp05P6
4. http://screenshot.sh/ouy8m3z6M1Nyy
5. http://screenshot.sh/odDJ1DqBBZJCW

But I need person who know about programming bots and I think I found right person :).
The idea of this site is get bots simple & fast Without register. Only using coupon verification If you bought bots and dont play now you can borrow the coupon to your friend so he can play :D.

I know person who made $7k/week for site like this but now I dont have contact to him so site like this make big profit :3.

Waiting for fast response :).

**Comment by hakca213** [comment]
ill help you

**Comment by hakca213** [comment]
how can i contact you i used to be a bot programmer i evenhow to make  know ip system that chither and bagar used so you dont need copoun verfication

**Comment by SlimxaQ** [comment]
@hakca213 Ok. https://discord.gg/PwZu5  join :) Btw. We can connect power and do it with You, Me, G047 But we can try solo If you want :) 👍

**Comment by hakca213** [comment]
we will team and do it :)

**Comment by SlimxaQ** [comment]
@hakca213 Yes! best agar.io bots on the WORLD!!!

**Comment by G047** [comment]
@SlimxaQ https://i.imgur.com/w3B1bHe.png

**Comment by SlimxaQ** [comment]
@G047 https://discord.gg/vTHCe

**Comment by fayizan** [comment]
@G047 so no more 300 free bots..?

**Comment by G047** [comment]
@SlimxaQ This is not relevant to this project
