### ISSUE TITLE
userscript 

### ISSUE THREAD

**Issue by Mystik21** [G047/Agar.io-Bots#2]
the userscript (client.user.js) doesn't work..agar.io not load!

**Comment by BreakAgar** [comment]
You need open start.bat

**Comment by Mystik21** [comment]
i have a error when i open start.bat...and the tampermonkey script doesn't work

**Comment by G047** [comment]
@Mystik21 Can you post the error here?

**Comment by Mystik21** [comment]
![immagine](https://cloud.githubusercontent.com/assets/22016209/18542640/43ee7096-7b2c-11e6-95f2-4ed6a5fa805a.png)
