### ISSUE TITLE
Help me Please!!

### ISSUE THREAD

**Issue by Jhair2015** [G047/Agar.io-Bots#25]
![captura](https://cloud.githubusercontent.com/assets/18153674/18617812/bfa0276a-7d9e-11e6-9b4a-9366ee553ff4.PNG)

**Comment by SutSug** [comment]
ikr

**Comment by anonymousxxx02** [comment]
Move proxies file or create new one in agar.io-bots-master folder

**Comment by RaxBoon** [comment]
![image](https://cloud.githubusercontent.com/assets/19439967/18618983/694dbcb2-7dbf-11e6-9c55-1b6d3a72d7b7.png)
Help me please

**Comment by fayizan** [comment]
@RaxBoon u have to load the userscript first into tampermonkey
userscript location `Server>files>client.user.js`

**Comment by RaxBoon** [comment]
![image](https://cloud.githubusercontent.com/assets/19439967/18639093/8d9b0d1c-7e60-11e6-8890-6466d5beeb92.png)
@fayizan
