### ISSUE TITLE
Help Me !!!!!!

### ISSUE THREAD

**Issue by RaxBoon** [G047/Agar.io-Bots#26]
![image](https://cloud.githubusercontent.com/assets/19439967/18618726/4fe2955e-7dba-11e6-9054-ca79e0d1ffe6.png)

**Comment by RaxBoon** [comment]
![image](https://cloud.githubusercontent.com/assets/19439967/18618907/36d09512-7dbe-11e6-89f9-831c9534e66d.png)
New Problem

**Comment by G047** [comment]
@RaxBoon Check proxies
