### ISSUE TITLE
I still have the same problem :(

### ISSUE THREAD

**Issue by Jhair2015** [G047/Agar.io-Bots#28]
![captura de pantalla 449](https://cloud.githubusercontent.com/assets/18153674/18619925/c13b6d1c-7dcd-11e6-9920-28e4fe3822ce.png)

**Comment by SutSug** [comment]
ikr

**Comment by fayizan** [comment]
@Jhair2015 u have to change the proxies,remove all the stock proxies and load fresh proxies

**Comment by G047** [comment]
@Jhair2015 You need fresh working http proxies that support connect
