### ISSUE TITLE
have a Huge Problem ? i dont get any proxies loaded at ALL

### ISSUE THREAD

**Issue by kaliduude** [G047/Agar.io-Bots#30]
i have Actually Installed Everything Nodejs 4..5.0 LTS and Python 2.7 and PIP
and install the Commands .. and they worked 100% 

but i have removed the proxies file already to the main Agar.io-Bots-master file
and my proxies are Fresh 100% HTTP/HTTPS and checked .. should i run them in either way or change the UUID or something? the other guys showed thier problem have an error with proxies at least... but i dont get anything why? just tell me please ,, i just runed the Server/server.js and python.py and going to the game creating party and nothing happends .. i mean at least for now i wanna get anything .. but it does not show
![problememm](https://cloud.githubusercontent.com/assets/17993365/18626216/487f606a-7e5c-11e6-9168-0513d128e4f2.PNG)

**Comment by TheRealDynamica** [comment]
python run.py doesnt work for me, and i installed everything.

**Comment by G047** [comment]
@kaliduude Can you contact me over the discord please?
