### ISSUE TITLE
Won't load!! not working

### ISSUE THREAD

**Issue by TheRealDynamica** [G047/Agar.io-Bots#32]
I installed everything and this happens... python run.py doesn't even work.

http://i.imgur.com/aaOzzhg.png

**Comment by yario-o** [comment]
Add python to path

**Comment by TheRealDynamica** [comment]
can i have a simple step by step to add path etc?

**Comment by yario-o** [comment]
http://superuser.com/questions/143119/how-to-add-python-to-the-windows-path

**Comment by TheRealDynamica** [comment]
thx, it started loading up and i choose about 20 bots just to test with 30+ working http proxys and loaded up and no bots loaded up or came to me... this a minor problem i've done or file?

**Comment by yario-o** [comment]
Did you add the userscript to tampermonkey?

**Comment by TheRealDynamica** [comment]
yes

**Comment by TheRealDynamica** [comment]
my skype is dynamicacraft if you want to see whats happening on my screen?
