### ISSUE TITLE
run.py changes

### ISSUE THREAD

**Issue by Battal51280TR** [G047/Agar.io-Bots#34]
i made some changes run.py here;

**Comment by RaxBoon** [comment]
send chages

**Comment by Battal51280TR** [comment]
how? i cant sen zip file :/

**Comment by RaxBoon** [comment]
send plis

**Comment by Battal51280TR** [comment]
![adsiz](https://cloud.githubusercontent.com/assets/18038517/18642788/bfcbdd80-7eaa-11e6-85fe-c6d04c3f0c13.png) this is a photo dont works :/ what i changed on run.py i added parentheses to prints and at the line 28 to for a in range(int(round(int(mem_gib / 2)))): this
