### ISSUE TITLE
 still happens the same :/

### ISSUE THREAD

**Issue by Jhair2015** [G047/Agar.io-Bots#36]
`Okay good, now  check the nodejs console; You should see 'Browser Connected UUID: XSAGHASGga' If this doesnt show two things could of happened, There patched OR You need to update your proxies :)
Opening browsers
Waiting at least 30 seconds for all the proxies to load
Assuming some of the proxies managed to connect, if you don't see 'Browser Connected UUID: GDSAeageAEag' at least a few times on the nodejs console you should update your proxies :)`

I get this and I can not go on, I did everything right, but not advance over there, opens a tabbed browser but are blank or not loaded

**Comment by G047** [comment]
It seams to be a problem with your proxies, private/elite proxies are suggested (make sure they are http
