### ISSUE TITLE
Console keep closing.

### ISSUE THREAD

**Issue by raphyjb** [G047/Agar.io-Bots#39]
Title says it all i cant open start.bat cuz its closing each time i open.. Not sure really how to install the node modules.. maybe do a mode-install.bat ?

**Comment by raphyjb** [comment]
+ the client doesnt even wanna work.

**Comment by Jhair2015** [comment]
@raphyjb open server.js need for the client to function properly

**Comment by RaxBoon** [comment]
I need help plis
![image](https://cloud.githubusercontent.com/assets/19439967/18669399/e00521d4-7f08-11e6-9384-7a0a838ce94a.png)

**Comment by anonymousxxx02** [comment]
@raphyjb open cmd in Agar.io-Bots folder and paste this  ` npm install express figlet serve-index socket.io readline  `

**Comment by raphyjb** [comment]
C:\Users\Maurice\Desktop\Agar.io-Bots-master>npm install express figlet serve-indexsocket.io readline
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express" "figlet" "serve-indexsocket.io" "readline"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/serve-indexsocket.io
npm ERR! 404
npm ERR! 404  'serve-indexsocket.io' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Maurice\Desktop\Agar.io-Bots-master\npm-debug.log

**Comment by raphyjb** [comment]
I did do it still nothing to do.
Can u add me on skype? my skype: raphyjb
or join discord asap: https://discordapp.com/invite/JMcVsuc

**Comment by MineMooreALT** [comment]
Just right click in the folder while holding shift click open command windows here and type node server/server.js then open run.py
