### ISSUE TITLE
Proxies are not loading.

### ISSUE THREAD

**Issue by boboftw** [G047/Agar.io-Bots#44]
I have all node_modules , node , python installed and all commands are working.
I entered HTTP proxies all elite and it does not load , here are some screens.
I also tried with proxy loading deelay , still won't work ..
![asd](https://cloud.githubusercontent.com/assets/17984526/18790563/f315bbc4-81b7-11e6-8654-ab6394e330c9.PNG)
![asdd](https://cloud.githubusercontent.com/assets/17984526/18790564/f3189a4c-81b7-11e6-8aa8-712175d9957a.PNG)
![asddd](https://cloud.githubusercontent.com/assets/17984526/18790562/f314ffea-81b7-11e6-8f8e-da24b3e48c79.PNG)

**Comment by yairnet** [comment]
i have same problem

**Comment by boboftw** [comment]
I resolved it , you need python 2.7.12 x32 or x64 , good luck.

**Comment by fayizan** [comment]
@boboftw show the proof or we dont believe..!!!
