### ISSUE TITLE
I jump me this and not continuous :(

### ISSUE THREAD

**Issue by Jhair2015** [G047/Agar.io-Bots#6]
I've done everything you ask me :)

However I jump me this and not continuous :(

Thank you for your great effort and work !!

![captura de pantalla 443](https://cloud.githubusercontent.com/assets/18153674/18564427/0a3b227a-7b51-11e6-84fa-d263aa9f05af.png)
![captura de pantalla 444](https://cloud.githubusercontent.com/assets/18153674/18564428/0a4455c0-7b51-11e6-9198-155f6cc77997.png)

WHAT AM I DOING WRONG?

**Comment by G047** [comment]
Try redownloading the script, if you get the same error check if chromedriver.exe is there; if not redownload. if all else fails come back w more info :)
