### ISSUE TITLE
my bots dont connect

### ISSUE THREAD

**Issue by Nick8fr32** [G047/Agar.io-Bots#7]
they i press how many rams i have and then it says browser connected, uuid: and then some random things 

and then i get 0 bots

**Comment by Wawy123** [comment]
idk i am testing them now XD

**Comment by G047** [comment]
Yeah agar patched my proxies, update coming in about 6 hours (hopefully

**Comment by Nick8fr32** [comment]
@G047 can u make it so we can use our own proxies?
